//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAlertingSystem.AlertingSystem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlertingSystem.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonitorPatientVitals", ReplyAction="http://tempuri.org/IService1/MonitorPatientVitalsResponse")]
        PatientRegistration.PatientAlertingSystem.PatientDetails[] MonitorPatientVitals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonitorPatientVitals", ReplyAction="http://tempuri.org/IService1/MonitorPatientVitalsResponse")]
        System.Threading.Tasks.Task<PatientRegistration.PatientAlertingSystem.PatientDetails[]> MonitorPatientVitalsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PatientAlertingSystem.AlertingSystem.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PatientAlertingSystem.AlertingSystem.IService1>, PatientAlertingSystem.AlertingSystem.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PatientRegistration.PatientAlertingSystem.PatientDetails[] MonitorPatientVitals() {
            return base.Channel.MonitorPatientVitals();
        }
        
        public System.Threading.Tasks.Task<PatientRegistration.PatientAlertingSystem.PatientDetails[]> MonitorPatientVitalsAsync() {
            return base.Channel.MonitorPatientVitalsAsync();
        }
    }
}
