// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProjectPatientAlertingSystem
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Discharge of the patient can happen from the GUI
        /// </summary>
        public void DischargePatient()
        {
            #region Variable Declarations
            WpfButton uIDischargeButton = this.UIBedLayoutWindow.UIDischargeButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Discharge' button
            Mouse.Click(uIDischargeButton, new Point(79, 8));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(36, 17));
        }
        
        #region Properties
        public UIBedLayoutWindow UIBedLayoutWindow
        {
            get
            {
                if ((this.mUIBedLayoutWindow == null))
                {
                    this.mUIBedLayoutWindow = new UIBedLayoutWindow();
                }
                return this.mUIBedLayoutWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBedLayoutWindow mUIBedLayoutWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIBedLayoutWindow : WpfWindow
    {
        
        public UIBedLayoutWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "BedLayout";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BedLayout");
            #endregion
        }
        
        #region Properties
        public WpfButton UIDischargeButton
        {
            get
            {
                if ((this.mUIDischargeButton == null))
                {
                    this.mUIDischargeButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDischargeButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "buttonDischargeBed8";
                    this.mUIDischargeButton.WindowTitles.Add("BedLayout");
                    #endregion
                }
                return this.mUIDischargeButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIDischargeButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
