// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AlertingSystemTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Tests the alerting system
        /// </summary>
        public void PatientAlerting()
        {
            #region Variable Declarations
            WpfButton uIResetAlertButton = this.UIMainWindowWindow.UIResetAlertButton;
            WpfButton uIUndoResetButton = this.UIMainWindowWindow.UIUndoResetButton;
            #endregion

            // Click 'Reset Alert' button
            Mouse.Click(uIResetAlertButton, new Point(43, 19));

            // Click 'Undo Reset' button
            Mouse.Click(uIUndoResetButton, new Point(45, 11));
        }
        
        #region Properties
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMainWindowWindow mUIMainWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UIResetAlertButton
        {
            get
            {
                if ((this.mUIResetAlertButton == null))
                {
                    this.mUIResetAlertButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIResetAlertButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "alertBed2";
                    this.mUIResetAlertButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIResetAlertButton;
            }
        }
        
        public WpfButton UIUndoResetButton
        {
            get
            {
                if ((this.mUIUndoResetButton == null))
                {
                    this.mUIUndoResetButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIUndoResetButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "undoAlertBed2";
                    this.mUIUndoResetButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIUndoResetButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIResetAlertButton;
        
        private WpfButton mUIUndoResetButton;
        #endregion
    }
}
